apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: part-02-service
  labels:
    app: replicat-set
    tier: part-02
spec:
  # modify replicas according to your case
  replicas: 4
  selector:
    matchLabels:
      tier: part-02
  template:
    metadata:
      labels:
        tier: part-02
    spec:
      containers:
        - name: replica-set-container
          image: registry.cluster.wik.cloud/public/echo
---
apiVersion: v1
kind: Service
metadata:
  name: replica-set-service
spec:
  selector:
    tier: part-02
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
